USE ShoeStoreDb
GO

IF EXISTS (SELECT * FROM Users WHERE UserId IS NULL)
    UPDATE Users SET UserId = 0 WHERE UserId IS NULL

IF EXISTS (SELECT * FROM Products WHERE Article IS NULL)
    UPDATE Products SET Article = 'TEMP' WHERE Article IS NULL

IF EXISTS (SELECT * FROM Orders WHERE OrderId IS NULL)
    UPDATE Orders SET OrderId = 0 WHERE OrderId IS NULL

IF EXISTS (SELECT * FROM OrderItems WHERE OrderId IS NULL OR Article IS NULL)
    DELETE FROM OrderItems WHERE OrderId IS NULL OR Article IS NULL
GO

UPDATE Orders SET OrderDate = '2025-02-28' WHERE OrderDate = '2025-02-30'
GO

ALTER TABLE Suppliers DROP COLUMN SupplierId
ALTER TABLE Suppliers ADD SupplierId INT IDENTITY(1,1) PRIMARY KEY
ALTER TABLE Suppliers ALTER COLUMN Name NVARCHAR(100) NOT NULL
GO

ALTER TABLE Manufacturers DROP COLUMN ManufacturerId
ALTER TABLE Manufacturers ADD ManufacturerId INT IDENTITY(1,1) PRIMARY KEY
ALTER TABLE Manufacturers ALTER COLUMN Name NVARCHAR(100) NOT NULL
GO

ALTER TABLE Categories DROP COLUMN CategoryId
ALTER TABLE Categories ADD CategoryId INT IDENTITY(1,1) PRIMARY KEY
ALTER TABLE Categories ALTER COLUMN Name NVARCHAR(50) NOT NULL
GO

ALTER TABLE Roles DROP COLUMN RoleId
ALTER TABLE Roles ADD RoleId INT IDENTITY(1,1) PRIMARY KEY
ALTER TABLE Roles ALTER COLUMN RoleName NVARCHAR(50) NOT NULL
GO

ALTER TABLE Customers DROP COLUMN CustomerId
ALTER TABLE Customers ADD CustomerId INT IDENTITY(1,1) PRIMARY KEY
ALTER TABLE Customers ALTER COLUMN FullName NVARCHAR(150) NOT NULL
GO

ALTER TABLE Users ALTER COLUMN UserId INT NOT NULL
ALTER TABLE Users ADD CONSTRAINT PK_Users PRIMARY KEY (UserId)
ALTER TABLE Users ALTER COLUMN FullName NVARCHAR(150) NOT NULL
ALTER TABLE Users ALTER COLUMN Login NVARCHAR(100) NOT NULL
ALTER TABLE Users ALTER COLUMN Password NVARCHAR(100) NOT NULL
ALTER TABLE Users ALTER COLUMN RoleId INT NOT NULL
GO

ALTER TABLE Products ALTER COLUMN Article NVARCHAR(20) NOT NULL
ALTER TABLE Products ADD CONSTRAINT PK_Products PRIMARY KEY (Article)
ALTER TABLE Products ALTER COLUMN Name NVARCHAR(200) NOT NULL
ALTER TABLE Products ALTER COLUMN Unit NVARCHAR(10) NOT NULL
ALTER TABLE Products ALTER COLUMN Price DECIMAL(10,2) NOT NULL
ALTER TABLE Products ALTER COLUMN SupplierId INT NOT NULL
ALTER TABLE Products ALTER COLUMN ManufacturerId INT NOT NULL
ALTER TABLE Products ALTER COLUMN CategoryId INT NOT NULL
ALTER TABLE Products ALTER COLUMN Discount INT NOT NULL
ALTER TABLE Products ALTER COLUMN Quantity INT NOT NULL
ALTER TABLE Products ALTER COLUMN Description NVARCHAR(MAX) NULL
ALTER TABLE Products ALTER COLUMN Photo NVARCHAR(500) NULL
GO

ALTER TABLE Orders DROP COLUMN OrderId
ALTER TABLE Orders ADD OrderId INT IDENTITY(1,1) PRIMARY KEY
ALTER TABLE Orders ALTER COLUMN OrderDate DATE NOT NULL
ALTER TABLE Orders ALTER COLUMN DeliveryDate DATE NULL
ALTER TABLE Orders ALTER COLUMN CustomerId INT NOT NULL
ALTER TABLE Orders ALTER COLUMN PickupCode INT NOT NULL
ALTER TABLE Orders ALTER COLUMN Status NVARCHAR(50) NOT NULL
GO

ALTER TABLE OrderItems ALTER COLUMN OrderId INT NOT NULL
ALTER TABLE OrderItems ALTER COLUMN Article NVARCHAR(20) NOT NULL
ALTER TABLE OrderItems ALTER COLUMN Quantity INT NOT NULL
ALTER TABLE OrderItems ADD CONSTRAINT PK_OrderItems PRIMARY KEY (OrderId, Article)
GO

ALTER TABLE Products ADD CONSTRAINT FK_Products_Suppliers FOREIGN KEY (SupplierId) REFERENCES Suppliers(SupplierId)
ALTER TABLE Products ADD CONSTRAINT FK_Products_Manufacturers FOREIGN KEY (ManufacturerId) REFERENCES Manufacturers(ManufacturerId)
ALTER TABLE Products ADD CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(CategoryId)
ALTER TABLE Users ADD CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId) REFERENCES Roles(RoleId)
ALTER TABLE Orders ADD CONSTRAINT FK_Orders_Customers FOREIGN KEY (CustomerId) REFERENCES Customers(CustomerId)
ALTER TABLE OrderItems ADD CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (OrderId) REFERENCES Orders(OrderId)
ALTER TABLE OrderItems ADD CONSTRAINT FK_OrderItems_Products FOREIGN KEY (Article) REFERENCES Products(Article)
GO